name: Deploy to Dev
on:
  push:
    branches: [dev]
jobs:
    get-details:
        runs-on: ubuntu-latest
        outputs:
            ORG_META: ${{ steps.step1.outputs.get-org-meta }}
        steps:
            - id: get-org-meta
              run: |
                token=eyJraWQiOiJMM0dWZlo2VzlQQzdiYm9RbVlSeFR2eWtiNUQ5VnhQZEg0XC9YeUh2SmVNWT0iLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiZ3RqQzVxaWFDdE1VY0ROQ3dkaWtHQSIsInN1YiI6Ijk5OTM4YjYzLTNiYWUtNDYxMi04MzcwLWU1MmYzMTFiMjg3ZiIsImNvZ25pdG86Z3JvdXBzIjpbInVzLXdlc3QtMl8zVXJ0dGpWcmZfVW5pYmxveC1EZXYiXSwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtd2VzdC0yLmFtYXpvbmF3cy5jb21cL3VzLXdlc3QtMl8zVXJ0dGpWcmYiLCJjb2duaXRvOnVzZXJuYW1lIjoidW5pYmxveC1kZXZfY3VxN3p4X3NqY3poZ3Vkd3pycG00bHAwM2FvNHVyZmR3dmpmc2ljeHducSIsIm9yaWdpbl9qdGkiOiJhNGNjNDJhNC1jZDI1LTRlMDktYmJlYS1hZjhkODc1ZWM4YTciLCJhdWQiOiI1Yzdmb3UzY3V0dHJicnVxc2ZnZWdkZGJnaiIsImlkZW50aXRpZXMiOlt7InVzZXJJZCI6IkN1UTd6WF9zSmNaSEdVRHd6cnBNNGxQMDNBTzRVUkZEV3ZKRnNpY3hXTlEiLCJwcm92aWRlck5hbWUiOiJVbmlibG94LURldiIsInByb3ZpZGVyVHlwZSI6Ik9JREMiLCJpc3N1ZXIiOm51bGwsInByaW1hcnkiOiJ0cnVlIiwiZGF0ZUNyZWF0ZWQiOiIxNjc3NzMzNTg0OTk3In1dLCJ0b2tlbl91c2UiOiJpZCIsImF1dGhfdGltZSI6MTY4NzUzOTgyNSwibmFtZSI6IlNodWJoYW0gU2luZ2giLCJleHAiOjE2ODgxOTk5MTQsImlhdCI6MTY4ODE5NjMxNCwianRpIjoiOWZiNzdhZjQtNGVhMS00OTY5LWI2NzUtMzdiMmJjNDU4NTY5IiwiZW1haWwiOiJzaHViaGFtLnNpbmdoQHVuaWJsb3guaW8ifQ.eUCLcM-EKqOeI4AyPovXLd3nmIU50M3vlPsgNPOzWwpXLSZTCauqu__vQT4gbdjX3FvAd8Bf4MpH96-X3LhyK5IbEquE-sxXptP252youICbKWH2NMFzY8oAku1BpaEByVFkTzWMiF0v17rDLDRt2XOOcGDJef5jBF0SWOsZHEBppvTr5bCKGUNPIaSNK-FrdZCiZAzFTyUuaVywEPzChxlkv71fzru939jPfREeCgZLPEZiprmiFT1AqcyfiQiD-gjqOjbZKacVN9RfNRlbTTWd3KO8e-1vc3Kb-tcZMTIOWudT_PMSB7Lfk9UY88oaZ3KPOKmzlMPMqqyDx5HSHQ
                curl --location 'https://yrxn4kq69j.execute-api.us-west-2.amazonaws.com/dev/admin/orgs/combi' \--header "Authorization: Bearer $token" >> "$GITHUB_OUTPUT"
            
    log-data:
        runs-on: ubuntu-latest
        needs: get-details
        steps:
            - env:
                OUTPUT1: ${{needs.get-details.outputs.ORG_META}}
              run: echo "$OUTPUT1"

    
