name: Deploy to Dev
on:
  push:
    branches: [development]
jobs:
    get-access-token:
        runs-on: ubuntu-latest
        outputs:
            ACCESS_TOKEN: ${{ steps.retrieve-access-token.outputs.ACCESS_TOKEN }}
        steps:
            - id: retrieve-access-token
              run: |
                ACCESS_TOKEN=$(curl --location 'https://dauth.uniblox.io/oauth2/token' \
                --header 'Content-Type: application/x-www-form-urlencoded' \
                --data '{
                      "grant_type": "client_credentials",
                      "client_id": ,
                      "client_secret": ,
                      "scope": "https://uniblox.io//ublox.ad.read"
                }' | jq '.data.access_token')

                echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_OUTPUT

    get-details:
        runs-on: ubuntu-latest
        outputs:
            BASE_URL: ${{ steps.get-org-meta.outputs.BASE_URL }}
            GA_ID: ${{ steps.get-org-meta.outputs.GA_ID }}
            COMPANY_CONTACT_EMAIL: ${{ steps.get-org-meta.outputs.COMPANY_CONTACT_EMAIL }}
            APP_LOGO: ${{ steps.get-org-meta.outputs.APP_LOGO }}
        steps:
            - id: get-org-meta
              run: |
                token=eyJraWQiOiJMM0dWZlo2VzlQQzdiYm9RbVlSeFR2eWtiNUQ5VnhQZEg0XC9YeUh2SmVNWT0iLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiV3dWMDNCRTF1V0JFN09XRjBqREZaQSIsInN1YiI6Ijk5OTM4YjYzLTNiYWUtNDYxMi04MzcwLWU1MmYzMTFiMjg3ZiIsImNvZ25pdG86Z3JvdXBzIjpbInVzLXdlc3QtMl8zVXJ0dGpWcmZfVW5pYmxveC1EZXYiXSwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtd2VzdC0yLmFtYXpvbmF3cy5jb21cL3VzLXdlc3QtMl8zVXJ0dGpWcmYiLCJjb2duaXRvOnVzZXJuYW1lIjoidW5pYmxveC1kZXZfY3VxN3p4X3NqY3poZ3Vkd3pycG00bHAwM2FvNHVyZmR3dmpmc2ljeHducSIsIm9yaWdpbl9qdGkiOiJhNGNjNDJhNC1jZDI1LTRlMDktYmJlYS1hZjhkODc1ZWM4YTciLCJhdWQiOiI1Yzdmb3UzY3V0dHJicnVxc2ZnZWdkZGJnaiIsImlkZW50aXRpZXMiOlt7InVzZXJJZCI6IkN1UTd6WF9zSmNaSEdVRHd6cnBNNGxQMDNBTzRVUkZEV3ZKRnNpY3hXTlEiLCJwcm92aWRlck5hbWUiOiJVbmlibG94LURldiIsInByb3ZpZGVyVHlwZSI6Ik9JREMiLCJpc3N1ZXIiOm51bGwsInByaW1hcnkiOiJ0cnVlIiwiZGF0ZUNyZWF0ZWQiOiIxNjc3NzMzNTg0OTk3In1dLCJ0b2tlbl91c2UiOiJpZCIsImF1dGhfdGltZSI6MTY4NzUzOTgyNSwibmFtZSI6IlNodWJoYW0gU2luZ2giLCJleHAiOjE2ODgyMDM5MTYsImlhdCI6MTY4ODIwMDMxNiwianRpIjoiYWU2NTRjMmQtNTQxNS00MWQ4LTgyZjMtODcxZmU2Mzc1OTk0IiwiZW1haWwiOiJzaHViaGFtLnNpbmdoQHVuaWJsb3guaW8ifQ.Kpc8Dy_Ax2aK-ONQANfXky9GCulOc9oSforK_BVxxJi67A0sbMAyVlmg8n92j0KE9Iy8xYo-N-iSTE2v7Lz4Amsfx0FbhiBPEwjOdoxP1w39d78x6PycgKP-BZ7ANvqBXfrGxAVMfUfee41dbwzk9DEkPDi6XasAPZmPGPY2H9NsfJMZ1kJ_MTe_9RUuPIP41zOYc-rgKor93Exv9UXmUUY7xxXtskcCeWg_xw8m3vmujW11OgX_Aqk8_bxxwp8GHYGPJZmwoQo54S7I3Fcpvey-SsaOxtGqlkM6livGds7rhR0DypfhXQr5UOUX5FBODIFVJR3DQXc6FxXyF1tNWA
                ORG_META=$(curl --location 'https://yrxn4kq69j.execute-api.us-west-2.amazonaws.com/dev/admin/orgs/combi' \--header "Authorization: Bearer $token")
                
                BASE_URL=$(curl --location 'https://yrxn4kq69j.execute-api.us-west-2.amazonaws.com/dev/admin/orgs/combi' \--header "Authorization: Bearer $token" | jq .data.BASE_URL)
                # BASE_URL=$(echo $ORG_META | jq .data.BASE_URL)
                GA_ID=$(echo $ORG_META | jq .data.GA_ID)
                COMPANY_CONTACT_EMAIL=$(echo $ORG_META | jq .data.COMPANY_CONTACT_EMAIL)
                APP_LOGO=$(echo $ORG_META | jq .data.APP_LOGO)
                
                echo "BASE_URL=$BASE_URL" >> $GITHUB_OUTPUT
                echo "GA_ID=$GA_ID" >> $GITHUB_OUTPUT
                echo "COMPANY_CONTACT_EMAIL=$COMPANY_CONTACT_EMAIL" >> $GITHUB_OUTPUT
                echo "APP_LOGO=$APP_LOGO" >> $GITHUB_OUTPUT
    log-data:
        runs-on: ubuntu-latest
        needs: get-details
        steps:
            - env:
                BASE_URL: ${{needs.get-details.outputs.BASE_URL}}
                GA_ID: ${{needs.get-details.outputs.GA_ID}}
                COMPANY_CONTACT_EMAIL: ${{needs.get-details.outputs.COMPANY_CONTACT_EMAIL}}
                APP_LOGO: ${{needs.get-details.outputs.APP_LOGO}}
              run: |
                echo $BASE_URL
                echo $GA_ID
                echo $COMPANY_CONTACT_EMAIL
                echo $APP_LOGO

    
