name: Deploy to Dev
on:
  push:
    branches: [development]
jobs:
    get-details:
        runs-on: ubuntu-latest
        outputs:
            BASE_URL: ${{ steps.get-org-meta.outputs.BASE_URL }}
        steps:
            - id: get-org-meta
              run: |
                token=eyJraWQiOiJMM0dWZlo2VzlQQzdiYm9RbVlSeFR2eWtiNUQ5VnhQZEg0XC9YeUh2SmVNWT0iLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiV3dWMDNCRTF1V0JFN09XRjBqREZaQSIsInN1YiI6Ijk5OTM4YjYzLTNiYWUtNDYxMi04MzcwLWU1MmYzMTFiMjg3ZiIsImNvZ25pdG86Z3JvdXBzIjpbInVzLXdlc3QtMl8zVXJ0dGpWcmZfVW5pYmxveC1EZXYiXSwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtd2VzdC0yLmFtYXpvbmF3cy5jb21cL3VzLXdlc3QtMl8zVXJ0dGpWcmYiLCJjb2duaXRvOnVzZXJuYW1lIjoidW5pYmxveC1kZXZfY3VxN3p4X3NqY3poZ3Vkd3pycG00bHAwM2FvNHVyZmR3dmpmc2ljeHducSIsIm9yaWdpbl9qdGkiOiJhNGNjNDJhNC1jZDI1LTRlMDktYmJlYS1hZjhkODc1ZWM4YTciLCJhdWQiOiI1Yzdmb3UzY3V0dHJicnVxc2ZnZWdkZGJnaiIsImlkZW50aXRpZXMiOlt7InVzZXJJZCI6IkN1UTd6WF9zSmNaSEdVRHd6cnBNNGxQMDNBTzRVUkZEV3ZKRnNpY3hXTlEiLCJwcm92aWRlck5hbWUiOiJVbmlibG94LURldiIsInByb3ZpZGVyVHlwZSI6Ik9JREMiLCJpc3N1ZXIiOm51bGwsInByaW1hcnkiOiJ0cnVlIiwiZGF0ZUNyZWF0ZWQiOiIxNjc3NzMzNTg0OTk3In1dLCJ0b2tlbl91c2UiOiJpZCIsImF1dGhfdGltZSI6MTY4NzUzOTgyNSwibmFtZSI6IlNodWJoYW0gU2luZ2giLCJleHAiOjE2ODgyMDM5MTYsImlhdCI6MTY4ODIwMDMxNiwianRpIjoiYWU2NTRjMmQtNTQxNS00MWQ4LTgyZjMtODcxZmU2Mzc1OTk0IiwiZW1haWwiOiJzaHViaGFtLnNpbmdoQHVuaWJsb3guaW8ifQ.Kpc8Dy_Ax2aK-ONQANfXky9GCulOc9oSforK_BVxxJi67A0sbMAyVlmg8n92j0KE9Iy8xYo-N-iSTE2v7Lz4Amsfx0FbhiBPEwjOdoxP1w39d78x6PycgKP-BZ7ANvqBXfrGxAVMfUfee41dbwzk9DEkPDi6XasAPZmPGPY2H9NsfJMZ1kJ_MTe_9RUuPIP41zOYc-rgKor93Exv9UXmUUY7xxXtskcCeWg_xw8m3vmujW11OgX_Aqk8_bxxwp8GHYGPJZmwoQo54S7I3Fcpvey-SsaOxtGqlkM6livGds7rhR0DypfhXQr5UOUX5FBODIFVJR3DQXc6FxXyF1tNWA
                response=$(curl --location 'https://yrxn4kq69j.execute-api.us-west-2.amazonaws.com/dev/admin/orgs/combi' \--header "Authorization: Bearer $token")
                curl --location 'https://yrxn4kq69j.execute-api.us-west-2.amazonaws.com/dev/admin/orgs/combi' \--header "Authorization: Bearer $token" | jq .data.BASE_URL
                BASE_URL=echo $response | jq .data.BASE_URL
                echo "BASE_URL=$BASE_URL" >> $GITHUB_OUTPUT
    log-data:
        runs-on: ubuntu-latest
        needs: get-details
        steps:
            - env:
                BASE_URL: ${{needs.get-details.outputs.BASE_URL}}
              run: |
                echo $BASE_URL
                echo "$BASE_URL"

    
